/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Avatar: typeof import('./src/components/ui/Avatar.vue')['default']
    Button: typeof import('./src/components/ui/Button.vue')['default']
    CallToAction: typeof import('./src/components/sections/CallToAction.vue')['default']
    Faqs: typeof import('./src/components/sections/Faqs.vue')['default']
    FeatureCard: typeof import('./src/components/FeatureCard.vue')['default']
    Features: typeof import('./src/components/sections/Features.vue')['default']
    Footer: typeof import('./src/components/sections/Footer.vue')['default']
    Hero: typeof import('./src/components/sections/Hero.vue')['default']
    Integrations: typeof import('./src/components/sections/Integrations.vue')['default']
    IntegrationsColumn: typeof import('./src/components/IntegrationsColumn.vue')['default']
    Introduction: typeof import('./src/components/sections/Introduction.vue')['default']
    LogoTicker: typeof import('./src/components/sections/LogoTicker.vue')['default']
    Navbar: typeof import('./src/components/sections/Navbar.vue')['default']
    Pointer: typeof import('./src/components/ui/Pointer.vue')['default']
    Tag: typeof import('./src/components/ui/Tag.vue')['default']
  }
}
